apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: infoline
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/infoline
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"
